eureka:
  client:
    enabled: false
    registerWithEureka: false
  fetchRegistry: false

# Server configuration
server:
  context-path: /micro
  port: ${SERVICE_PORT:8081}

management:
  port: ${MANAGEMENT_PORT:8091}

# Spring properties
spring:
  application:
    name: catalog

# Elasticsearch
elasticsearch:
  url: ${ES_URL:http://127.0.0.1:9200}
  user: ${ES_USER:}
  password: ${ES_PASSWORD:}
  index: ${ES_INDEX:micro}
  doc_type: ${ES_DOC_TYPE:items}

inventoryService:
  url: ${INVENTORY_URL:http://127.0.0.1:8080}
