{{- if or .Values.elasticsearch.password .Values.elasticsearch.cacertificatebase64 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "catalog.fullname" . }}-elasticsearch-secret
  labels:
    {{- include "catalog.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.elasticsearch.password }}
  elasticsearch-password: {{ .Values.elasticsearch.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.elasticsearch.cacertificatebase64 }}
  elasticsearch-ca-certificate: {{ .Values.elasticsearch.cacertificatebase64 | b64enc | quote }}
  {{- end }}
{{- end }}